apiVersion: apps/v1
kind: Deployment
metadata:
  name: configserver-deployment
  labels:
    app: configserver
spec:
  replicas: 1
  selector:
    matchLabels:
      app: configserver
  template:
    metadata: 
      labels:
        app: configserver
    spec: 
      containers:
        - name: configserver
          image: miguelmazo/configserver
          ports:
          - containerPort: 8071